spring:
  application:
    name: coupon-service

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dynamic:
      primary: test2 #设置默认的数据源或者数据源组,默认值即为master
      strict: false  #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        test1:
#          url: jdbc:mysql://testdbhw.gooeto.com:13306/juse_discount?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          url: jdbc:mysql://localhost:3306/local-coupon?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456
        test2:
          url: jdbc:mysql://localhost:3306/coupon-2?useUnicode=true&useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: 123456


    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
#  redis:
#    host: 127.0.0.1
#    port: 6379
#    timeout: 20000
#    password:
#    database: 0
#    maxIdle: 8
#    maxActive: 10
#    maxTotal: 5
#    maxWaitMillis: 30000
#    minEvictableIdleTimeMillis:
#    numTestsPerEvictionRun: 10
#    timeBetweenEvictionRunsMillis: 10
#    testOnBorrow: true
#    testWhileIdle: true
server:
  port: 9000
#mybatis-plus:
#  mapper-locations: classpath*:mapper/xml/*Mapper.xml

mybatis-plus:
  mapper-locations: classpath*:com/jusekj/coupon/**/mapper/xml/*.xml


